"""python3 -m unittest tests.test_mcp -v

Drives the Relay MCP server the way a harness does: spawns `python3 -m relay.mcp`, speaks newline-delimited
JSON-RPC over its stdin/stdout, and checks that stdout carries nothing but protocol messages. Offline: mock
providers only, and every env var that could reach the network is removed.
"""
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from relay import mcp
from relay.plan import parse

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
SAVINGS_LEDGER = EXAMPLES / "savings-demo" / "events.jsonl"
NETWORK_ENV = ("AGENT37_API_KEY", "SUPABASE_URL", "SUPABASE_KEY", "SUPABASE_SERVICE_ROLE_KEY", "GITHUB_TOKEN")


def offline_env(**extra: str) -> dict:
    env = {k: v for k, v in os.environ.items() if k not in NETWORK_ENV and k != mcp.ALLOW_BURN_ENV}
    env.update(NO_COLOR="1", **extra)
    return env


def req(rid, method, params=None) -> dict:
    m = {"jsonrpc": "2.0", "id": rid, "method": method}
    if params is not None:
        m["params"] = params
    return m


def note(method) -> dict:
    return {"jsonrpc": "2.0", "method": method}


def call(rid, name, **arguments) -> dict:
    return req(rid, "tools/call", {"name": name, "arguments": arguments})


INIT = req(1, "initialize", {"protocolVersion": "2025-06-18", "capabilities": {},
                             "clientInfo": {"name": "relay-tests", "version": "0"}})


def run_stdio(lines: list, workspace: str, env: dict, timeout: float = 180) -> tuple[list[dict], subprocess.CompletedProcess]:
    """Spawn the server, feed it every line, close stdin; return the parsed stdout messages."""
    data = "".join((m if isinstance(m, str) else json.dumps(m)) + "\n" for m in lines)
    proc = subprocess.run([sys.executable, "-m", "relay.mcp", "-C", workspace], input=data, capture_output=True,
                          text=True, cwd=ROOT, env=env, timeout=timeout)
    out = []
    for line in proc.stdout.splitlines():
        msg = json.loads(line)                      # any stray print on stdout fails here
        assert msg.get("jsonrpc") == "2.0", line
        out.append(msg)
    return out, proc


def fixture_month() -> str:
    """The month examples/savings-demo covers (it is regenerated by demo/make_savings_fixture.py)."""
    from datetime import datetime, timezone
    first = json.loads(SAVINGS_LEDGER.read_text().splitlines()[0])
    return datetime.fromtimestamp(first["ts"], timezone.utc).strftime("%Y-%m")


def text(resp: dict) -> str:
    return "".join(c["text"] for c in resp["result"]["content"] if c["type"] == "text")


class StdioSession(unittest.TestCase):
    """One harness session over real stdio: handshake, discovery, queue work, review it, value, burn, errors."""

    @classmethod
    def setUpClass(cls):
        cls.ws = tempfile.mkdtemp()
        cls.month = fixture_month()
        cls.msgs, cls.proc = run_stdio([
            INIT,
            note("notifications/initialized"),
            note("notifications/some_future_thing"),
            req(2, "tools/list"),
            call(3, "relay_plan_add", plan="PLAN.md", project="greet-cli", task="add a --shout flag"),
            call(4, "relay_plan_add", plan="PLAN.md", project="greet-cli", task="add a --shout flag"),
            call(5, "relay_plan_add", plan="PLAN.md", project="docs", task="write a README with usage"),
            call(6, "relay_plan_list", plan="PLAN.md"),
            call(7, "relay_savings", month=cls.month, ledger=str(SAVINGS_LEDGER), include_claude=False),
            call(8, "relay_burn", plan="PLAN.md", now=True),
            call(9, "relay_burn", plan="PLAN.md"),
            req(10, "relay/does_not_exist"),
            req(11, "ping"),
            call(12, "relay_teleport"),
            "this is not json",
            call(13, "relay_plan_list"),
        ], cls.ws, offline_env())
        cls.by_id = {m.get("id"): m for m in cls.msgs}

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.ws, ignore_errors=True)

    def test_stdout_is_only_protocol_and_server_exits_cleanly_on_eof(self):
        self.assertEqual(self.proc.returncode, 0, self.proc.stderr)
        # notifications get no reply; every request gets exactly one, in order
        self.assertEqual([m.get("id") for m in self.msgs], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, None, 13])
        self.assertIn("relay.mcp:", self.proc.stderr)   # logs go to stderr

    def test_initialize(self):
        r = self.by_id[1]["result"]
        self.assertEqual(r["protocolVersion"], "2025-06-18")
        self.assertEqual(r["serverInfo"]["name"], "relay")
        self.assertIn("tools", r["capabilities"])
        self.assertTrue(r["instructions"])

    def test_tools_list(self):
        tools = self.by_id[2]["result"]["tools"]
        self.assertEqual({t["name"] for t in tools},
                         {"relay_capacity", "relay_savings", "relay_plan_list", "relay_plan_add", "relay_burn"})
        for t in tools:
            self.assertEqual(t["inputSchema"]["type"], "object", t["name"])
            self.assertIn("properties", t["inputSchema"])
            self.assertTrue(t["description"])

    def test_plan_add_then_list(self):
        for rid in (3, 4, 5):
            self.assertFalse(self.by_id[rid]["result"]["isError"], text(self.by_id[rid]))
        self.assertIn("created", text(self.by_id[3]))
        self.assertIn("already queued", text(self.by_id[4]))
        plan = Path(self.ws) / "PLAN.md"
        self.assertTrue(plan.read_text().startswith("# Night shift plan\n"))
        pl = parse(plan)
        self.assertEqual([(p.name, t.text) for p, t in pl.queue],
                         [("greet-cli", "add a --shout flag"), ("docs", "write a README with usage")])
        listing = text(self.by_id[6])
        self.assertFalse(self.by_id[6]["result"]["isError"])
        self.assertIn("## greet-cli", listing)
        self.assertIn("- [ ] add a --shout flag", listing)
        self.assertIn("- [ ] write a README with usage", listing)
        self.assertIn("2 queued", listing)

    def test_savings_fixture(self):
        from relay import value
        self.assertFalse(self.by_id[7]["result"]["isError"])
        m = value.month(self.month, [str(SAVINGS_LEDGER)], include_claude=False)
        self.assertGreater(m.used_usd, 100)                       # the fixture is a real month, not an empty one
        self.assertIn(value.money(m.used_usd), text(self.by_id[7]))   # e.g. "$1,942.00"
        self.assertEqual(text(self.by_id[7]), value.render(m, color=False))
        self.assertNotIn("\x1b[", text(self.by_id[7]))

    def test_burn_refuses_without_opt_in(self):
        r = self.by_id[8]["result"]
        self.assertTrue(r["isError"])
        self.assertIn(mcp.ALLOW_BURN_ENV, text(self.by_id[8]))
        self.assertIn("Refused", text(self.by_id[8]))
        self.assertFalse((Path(self.ws) / "MORNING.md").exists())     # nothing ran

    def test_burn_without_now_returns_schedule_commands(self):
        r = self.by_id[9]["result"]
        self.assertFalse(r["isError"])
        self.assertIn("agent37.py", text(self.by_id[9]))
        self.assertIn("schedule --at 23:00", text(self.by_id[9]))
        self.assertIn("burn run PLAN.md", text(self.by_id[9]))

    def test_protocol_errors(self):
        self.assertEqual(self.by_id[10]["error"]["code"], -32601)       # unknown method
        self.assertEqual(self.by_id[11]["result"], {})                   # ping
        self.assertEqual(self.by_id[12]["error"]["code"], -32602)       # unknown tool
        self.assertEqual(self.msgs[-2]["error"]["code"], -32700)        # parse error, id null
        self.assertTrue(self.by_id[13]["result"]["isError"])            # missing required argument
        self.assertIn("plan", text(self.by_id[13]))


class Interactive(unittest.TestCase):
    def test_replies_arrive_while_stdin_stays_open(self):
        """Harnesses wait for each reply before sending the next request; nothing may sit in a buffer."""
        import queue
        import threading
        p = subprocess.Popen([sys.executable, "-m", "relay.mcp"], cwd=ROOT, env=offline_env(),
                             stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
        self.addCleanup(p.kill)
        lines: "queue.Queue[bytes]" = queue.Queue()
        threading.Thread(target=lambda: [lines.put(b) for b in iter(p.stdout.readline, b"")], daemon=True).start()

        def rpc(msg):
            p.stdin.write((json.dumps(msg) + "\n").encode())
            p.stdin.flush()
            return json.loads(lines.get(timeout=10))

        self.assertEqual(rpc(INIT)["result"]["serverInfo"]["name"], "relay")
        p.stdin.write((json.dumps(note("notifications/initialized")) + "\n").encode())
        self.assertEqual(len(rpc(req(2, "tools/list"))["result"]["tools"]), 5)
        self.assertEqual(rpc(req(3, "ping")), {"jsonrpc": "2.0", "id": 3, "result": {}})
        p.stdin.close()
        self.assertEqual(p.wait(timeout=10), 0)
        p.stdout.close()

    @unittest.skipUnless(os.name == "posix", "closes fd 2 in the child")
    def test_serves_when_started_with_stderr_closed(self):
        """Some launchers close stderr; stray output must still never reach stdout, and the loop must still run."""
        ws = tempfile.mkdtemp()
        self.addCleanup(shutil.rmtree, ws, True)
        data = "".join(json.dumps(m) + "\n" for m in [
            INIT, call(2, "relay_plan_add", plan="PLAN.md", project="p", task="t"), req(3, "ping")])
        proc = subprocess.run([sys.executable, "-m", "relay.mcp", "-C", ws], input=data, capture_output=True,
                              text=True, cwd=ROOT, env=offline_env(), timeout=30, preexec_fn=lambda: os.close(2))
        self.assertEqual(proc.returncode, 0)
        msgs = [json.loads(line) for line in proc.stdout.splitlines()]
        self.assertEqual([m["id"] for m in msgs], [1, 2, 3], proc.stdout)
        self.assertFalse(msgs[1]["result"]["isError"])


class InProcess(unittest.TestCase):
    """The same loop over in-memory streams, plus plan-editing edge cases."""

    def setUp(self):
        self.ws = Path(tempfile.mkdtemp())
        self.server = mcp.Server(self.ws)
        self.addCleanup(shutil.rmtree, self.ws, True)
        quiet = mock.patch.object(mcp, "log")
        quiet.start()
        self.addCleanup(quiet.stop)

    def serve(self, *msgs) -> list[dict]:
        out = io.BytesIO()
        mcp.serve(io.BytesIO("".join(json.dumps(m) + "\n" for m in msgs).encode()), out, self.server)
        return [json.loads(line) for line in out.getvalue().decode().splitlines()]

    def tool(self, name, **args) -> tuple[str, bool]:
        r = self.server.handle(call(1, name, **args))["result"]
        return r["content"][0]["text"], r["isError"]

    def test_serve_in_memory(self):
        replies = self.serve(INIT, note("notifications/initialized"), req(2, "tools/list"), req(3, "nope"))
        self.assertEqual([r["id"] for r in replies], [1, 2, 3])
        self.assertEqual(len(replies[1]["result"]["tools"]), 5)
        self.assertEqual(replies[2]["error"]["code"], -32601)
        self.assertTrue(self.server.initialized)

    def test_version_negotiation(self):
        old = self.server.handle(req(1, "initialize", {"protocolVersion": "2024-11-05"}))["result"]
        self.assertEqual(old["protocolVersion"], "2024-11-05")
        unknown = self.server.handle(req(1, "initialize", {"protocolVersion": "1999-01-01"}))["result"]
        self.assertEqual(unknown["protocolVersion"], "2025-06-18")

    def test_invalid_requests(self):
        self.assertEqual(self.server.handle({"id": 1, "method": "ping"})["error"]["code"], -32600)
        self.assertEqual(self.server.handle({"jsonrpc": "2.0", "id": 1})["error"]["code"], -32600)
        self.assertIsNone(self.server.handle({"jsonrpc": "2.0", "id": 9, "result": {}}))   # stray response
        batch = self.server.handle([req(1, "ping"), note("notifications/initialized"), req(2, "ping")])
        self.assertEqual([r["id"] for r in batch], [1, 2])

    def test_plan_add_inserts_under_existing_project(self):
        plan = self.ws / "PLAN.md"
        shutil.copy(EXAMPLES / "PLAN.md", plan)
        before = plan.read_text().splitlines()
        msg, err = self.tool("relay_plan_add", plan="PLAN.md", project="landing-page", task="add a FAQ section")
        self.assertFalse(err, msg)
        after = plan.read_text().splitlines()
        self.assertEqual(len(after), len(before) + 1)
        i = after.index("- [ ] add a FAQ section")
        self.assertEqual(after[i - 1], "- [ ] add a pricing section")
        pl = parse(plan)
        landing = next(p for p in pl.projects if p.name == "landing-page")
        self.assertEqual([t.text for t in landing.tasks][-1], "add a FAQ section")
        self.assertEqual(landing.test, 'grep -q "<h1" index.html')           # project config untouched
        self.assertEqual(len(next(p for p in pl.projects if p.name == "api-stub").tasks), 1)

    def test_plan_add_project_without_tasks_and_new_project(self):
        plan = self.ws / "PLAN.md"
        plan.write_text("# Mine\n\n## alpha\nrepo: https://example.invalid/alpha\n## beta\n- [x] shipped")
        self.assertFalse(self.tool("relay_plan_add", plan="PLAN.md", project="ALPHA", task="first\ntask")[1])
        self.assertFalse(self.tool("relay_plan_add", plan="PLAN.md", project="gamma", task="- [ ] third")[1])
        pl = parse(plan)
        tasks = {p.name: [(t.text, t.state) for t in p.tasks] for p in pl.projects}
        self.assertEqual(tasks, {"alpha": [("first task", " ")], "beta": [("shipped", "x")],
                                 "gamma": [("third", " ")]})
        self.assertEqual(pl.projects[0].repo, "https://example.invalid/alpha")
        self.assertIn("\n\n## beta", plan.read_text())
        listing, err = self.tool("relay_plan_list", plan="PLAN.md")
        self.assertFalse(err)
        self.assertIn("1 done", listing)

    def test_plan_list_missing_plan_is_tool_error(self):
        msg, err = self.tool("relay_plan_list", plan="nope.md")
        self.assertTrue(err)
        self.assertIn("relay_plan_add", msg)

    def test_argument_validation(self):
        for args, why in [({"plan": "P.md", "project": "p", "task": "  "}, "empty"),
                          ({"plan": 3, "project": "p", "task": "t"}, "must be a string"),
                          ({"plan": "P.md", "project": "p", "task": "t", "colour": "red"}, "unknown argument")]:
            msg, err = self.tool("relay_plan_add", **args)
            self.assertTrue(err)
            self.assertIn(why, msg)
        msg, err = self.tool("relay_savings", month="October")
        self.assertTrue(err)
        msg, err = self.tool("relay_burn", plan="P.md", max_tasks=0)
        self.assertTrue(err)

    def test_plan_add_only_writes_markdown(self):
        """The plan path comes from the model: it must never append checklist lines (with backticks) to a shell rc."""
        rc = self.ws / ".zshrc"
        rc.write_text("export FOO=1\n")
        msg, err = self.tool("relay_plan_add", plan=str(rc), project="setup", task="verify `touch /tmp/x` works")
        self.assertTrue(err)
        self.assertIn("markdown", msg)
        self.assertEqual(rc.read_text(), "export FOO=1\n")
        self.assertTrue(self.tool("relay_plan_add", plan="notes.txt", project="a", task="b")[1])
        self.assertFalse((self.ws / "notes.txt").exists())
        (self.ws / "SNEAKY.md").symlink_to(rc)                                   # a .md name pointing at the rc
        self.assertTrue(self.tool("relay_plan_add", plan="SNEAKY.md", project="a", task="b")[1])
        self.assertEqual(rc.read_text(), "export FOO=1\n")
        self.assertFalse(self.tool("relay_plan_add", plan="Plan.MARKDOWN", project="## api", task="t")[1])
        self.assertIn("\n## api\n", (self.ws / "Plan.MARKDOWN").read_text())     # not '## ## api'

    def test_plan_add_keeps_symlink_and_permissions(self):
        vault = self.ws / "vault"
        vault.mkdir()
        real = vault / "PLAN.md"
        real.write_text("# Vault\n\n## api\n- [ ] one\n")
        real.chmod(0o600)
        (self.ws / "PLAN.md").symlink_to(real)
        self.assertFalse(self.tool("relay_plan_add", plan="PLAN.md", project="api", task="two")[1])
        self.assertTrue((self.ws / "PLAN.md").is_symlink())
        self.assertEqual(real.read_text(), "# Vault\n\n## api\n- [ ] one\n- [ ] two\n")
        self.assertEqual(real.stat().st_mode & 0o777, 0o600)
        self.assertEqual([p.name for p in self.ws.iterdir() if p.name.endswith("relay-tmp")], [])

    def test_strict_argument_values(self):
        self.assertTrue(self.tool("relay_savings", month="2026-09\n", include_claude=False)[1])   # no '$' slack
        msg, err = self.tool("relay_burn", plan="P.md", hours=float("nan"))
        self.assertTrue(err)
        self.assertIn("must be a number", msg)
        self.assertIn("an integer", self.tool("relay_burn", plan="P.md", max_tasks="2")[0])

    def test_unknown_tool_shapes_and_probed_lists(self):
        for name in (["relay_plan_list"], {"x": 1}, None):
            self.assertEqual(self.server.handle(req(1, "tools/call", {"name": name}))["error"]["code"], -32602)
        self.assertEqual(self.server.handle(req(2, "resources/list"))["result"], {"resources": []})
        self.assertEqual(self.server.handle(req(3, "resources/templates/list"))["result"], {"resourceTemplates": []})
        self.assertEqual(self.server.handle(req(4, "prompts/list"))["result"], {"prompts": []})

    def test_schedule_follows_the_burner_window(self):
        """The Agent37 cron starts the shift with --now, so it must fire when the downtime opens, in its zone."""
        (self.ws / "burner.json").write_text(json.dumps(
            {"idle": {"weekday": "01:30-08:00", "weekend": "all", "timezone": "Europe/Berlin"}}))
        msg, err = self.tool("relay_burn", plan="PLAN.md")
        self.assertFalse(err, msg)
        self.assertIn("schedule --at 01:30 --tz Europe/Berlin", msg)
        self.assertIn("(Europe/Berlin)", msg)
        (self.ws / "b2.json").write_text(json.dumps({"idle": {"weekday": "22:15-06:00"}}))
        with mock.patch.dict(os.environ, {"TZ": "UTC"}):
            msg, _ = self.tool("relay_burn", plan="PLAN.md", burner="b2.json")
        self.assertIn("schedule --at 22:15 --tz UTC", msg)
        self.assertIn("no idle.timezone", msg)
        self.assertNotIn("America/Los_Angeles", msg)

    def test_capacity_report(self):
        with mock.patch.dict(os.environ, {}, clear=False):
            for k in NETWORK_ENV:
                os.environ.pop(k, None)
            msg, err = self.tool("relay_capacity", burner=str(EXAMPLES / "burner-demo.json"))
        self.assertFalse(err, msg)
        self.assertIn("downtime window", msg)
        self.assertIn("agent37", msg)
        msg, err = self.tool("relay_capacity")
        self.assertTrue(err)
        self.assertIn("burner config not found", msg)


class BurnOptIn(unittest.TestCase):
    def test_burn_runs_with_opt_in_and_child_processes_never_touch_stdout(self):
        ws = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, ws, True)
        shutil.copy(EXAMPLES / "PLAN.md", ws / "PLAN.md")
        shutil.copy(EXAMPLES / "burner-demo.json", ws / "burner.json")
        msgs, proc = run_stdio([
            INIT,
            call(2, "relay_burn", plan="PLAN.md"),                           # opted in, but now not set: schedule only
            call(3, "relay_burn", plan="PLAN.md", now=True, max_tasks=2),
        ], str(ws), offline_env(**{mcp.ALLOW_BURN_ENV: "1"}))
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertEqual([m["id"] for m in msgs], [1, 2, 3])
        self.assertIn("Not started", text(msgs[1]))
        self.assertNotIn("restart this server", text(msgs[1]))                # it is already opted in
        r = msgs[2]["result"]
        self.assertFalse(r["isError"], text(msgs[2]))
        self.assertIn("2 done", text(msgs[2]))
        self.assertIn("Good morning", text(msgs[2]))
        self.assertTrue((ws / "MORNING.md").exists())
        self.assertTrue((ws / ".relay" / "mcp-burn.log").exists())
        self.assertIn("- [x] scaffold greet.py", (ws / "PLAN.md").read_text())
        rows = [json.loads(line) for line in (ws / ".relay" / "events.jsonl").read_text().splitlines()]
        self.assertTrue(any(r["event"] == "call" and "usd" in r for r in rows))


if __name__ == "__main__":
    unittest.main()
